Thrive: {
	p_kiwi: Kiwi
	p_pomona: Pomona Island
	p_rona: Rona Island
	p_mainland: Mainland
	p_people: Humanity

	p_kiwi <-> p_pomona
	p_kiwi <-> p_rona
	p_kiwi <-> p_people
	p_kiwi <-> p_mainland
	p_pomona <-> p_rona
	p_pomona <-> p_people
	p_pomona <-> p_mainland
	p_rona <-> p_people
	p_rona <-> p_mainland

}
Thrive.shape: circle
Thrive.p_kiwi.shape: diamond
Thrive.p_pomona.shape: oval
Thrive.p_rona.shape: oval
Thrive.p_people.shape: person